name: CI
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

    - name: Check code quality
      uses: pre-commit/action@v3.0.1

    - name: Run tests
      run: pytest -v
